#!/bin/bash

export packageFriendlyName="Issabel Framework"
export packageName="PACKAGE_NAME"
export version="VERSION_NUMBER"
export release="RELEASE_NUMBER"
export fullVersionName="$version-$release"
export folderName="$packageName-$fullVersionName"
